### ISSUE TITLE
Error while running python3 mange.py makemigrations

### ISSUE THREAD

**Issue by ponty96** [DrkSephy/django-hackathon-starter#26]
```
Traceback (most recent call last):
File "manage.py", line 10, in <module>
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 351, in      execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 325, in execute
django.setup()
File "/usr/local/lib/python3.4/dist-packages/django/__init__.py", line 18, in setup
apps.populate(settings.INSTALLED_APPS)
File "/usr/local/lib/python3.4/dist-packages/django/apps/registry.py", line 85, in populate
app_config = AppConfig.create(entry)
File "/usr/local/lib/python3.4/dist-packages/django/apps/config.py", line 86, in create
module = import_module(entry)
File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'bootstrapform'
```

**Comment by kootenpv** [comment]
I think using `pip3 install -r requirements` already gave an error on that module.

**Comment by DrkSephy** [comment]
As mentioned in #29, the underlying libraries used for OAuth in this project don't have support for Python 3. As such, you're unfortunately locked to using Python 2.x for Django Hackathon Starter. If there is any way I can fix this in the future, I will do so. Thanks!
